### ISSUE TITLE
Bitwig 1.3.9 fails to start

### ISSUE THREAD

**Issue by samtuke** [stevechambers/fedora-inst-bitwig#4]
After installing using the script, I run bitwig-studio and get:

`$ bitwig-studio
JRE Path: //opt/bitwig-studio/lib/jre
Could not de-obfuscate stack trace: /home/samtuke/.BitwigStudio/8f260affd623f32c54eee3c11b577f4ff18647dc-Linux-release.txt not found.
Could not de-obfuscate stack trace: /home/samtuke/.BitwigStudio/8f260affd623f32c54eee3c11b577f4ff18647dc-Linux-release.txt not found.
java.lang.UnsatisfiedLinkError: /opt/bitwig-studio/lib/bitwig-studio/libx11-windowing-system.so: libbz2.so.1.0: cannot open shared object file: No such file or directory
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at bDx.AQL(SourceFile:186)
    at com.bitwig.x11_windowing_system.X11WindowingSystem.AQL(SourceFile:20)
    at com.bitwig.x11_windowing_system.X11WindowingSystem.<clinit>(SourceFile:14)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at com.bitwig.windowing_system.zu.w2z(SourceFile:151)
    at com.bitwig.windowing_system.zu.<clinit>(SourceFile:42)
    at com.bitwig.flt.app.FloatMainApplication.YKl(SourceFile:653)
    at bQU.sMZ(SourceFile:73)
    at com.bitwig.flt.app.FloatMainApplication.sMZ(SourceFile:672)
    at bNn.wJk(SourceFile:2029)
    at bNn.AQL(SourceFile:147)
    at bNF.run(SourceFile:873)
    at bNn.w2z(SourceFile:1275)
    at com.bitwig.flt.app.UiI.w2z(SourceFile:1378)
    at bNn.AQL(SourceFile:1219)
    at bNn.rqi(SourceFile:877)
    at com.bitwig.flt.app.FloatMainApplication.main(SourceFile:6432)`

**Comment by samtuke** [comment]
Can be fixed with:
`cd /usr/lib64/
ln -s libbz2.so.1 libbz2.so.1.0`

**Comment by stevechambers** [comment]
Thanks for this - can you let me know which version of Fedora you saw this behaviour on?

**Comment by samtuke** [comment]
Fedora 23 Workstation 64 bit, Gnome 3. Thanks!
